######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 23:29:28 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Klass.h
SOURCES += main.cpp
